"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const tabs = require("./tabs.qwik.cjs");
const tabPanel = require("./tab-panel.qwik.cjs");
const tabsList = require("./tabs-list.qwik.cjs");
const tab = require("./tab.qwik.cjs");
exports.Root = tabs.Tabs;
exports.Panel = tabPanel.TabPanel;
exports.List = tabsList.TabList;
exports.Tab = tab.Tab;
