"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const carousel = require("./carousel.qwik.cjs");
const carouselViewport = require("./carousel-viewport.qwik.cjs");
const carouselContainer = require("./carousel-container.qwik.cjs");
const slide = require("./slide.qwik.cjs");
const prevButton = require("./prev-button.qwik.cjs");
const nextButton = require("./next-button.qwik.cjs");
const pagination = require("./pagination.qwik.cjs");
exports.Root = carousel.Carousel;
exports.View = carouselViewport.CarouselView;
exports.Container = carouselContainer.CarouselContainer;
exports.Slide = slide.CarouselSlide;
exports.Prev = prevButton.CarouselPrev;
exports.Next = nextButton.CarouselNext;
exports.Pagination = pagination.CarouselPagination;
