"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const accordionRoot = require("./accordion-root.qwik.cjs");
const accordionHeader = require("./accordion-header.qwik.cjs");
const accordionItem = require("./accordion-item.qwik.cjs");
const accordionTrigger = require("./accordion-trigger.qwik.cjs");
const accordionContent = require("./accordion-content.qwik.cjs");
exports.Root = accordionRoot.AccordionRoot;
exports.Header = accordionHeader.AccordionHeader;
exports.Item = accordionItem.AccordionItem;
exports.Trigger = accordionTrigger.AccordionTrigger;
exports.Content = accordionContent.AccordionContent;
