"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const collapsible = require("./collapsible.qwik.cjs");
const collapsibleContent = require("./collapsible-content.qwik.cjs");
const collapsibleTrigger = require("./collapsible-trigger.qwik.cjs");
const collapsibleContextId = require("./collapsible-context-id.qwik.cjs");
exports.Root = collapsible.Collapsible;
exports.Content = collapsibleContent.CollapsibleContent;
exports.Trigger = collapsibleTrigger.CollapsibleTrigger;
exports.collapsibleContextId = collapsibleContextId.collapsibleContextId;
